version: "3.8"
services:
  db:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=mypassword"
    ports:
      - 5432:5432
  myflyway:
    depends_on:
      - db
    environment:
      - "FLYWAY_URL=jdbc:postgresql://db/"
      - "FLYWAY_SCHEMAS=todo"
      - "FLYWAY_DEFAULT_SCHEMA=todo"
      - "FLYWAY_USER=postgres"
      - "FLYWAY_PASSWORD=mypassword"
      - "FLYWAY_CONNECT_RETRIES=60"
