version: "3.8"
services:
  db:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=mypassword"
    ports:
      - 5432:5432
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/ -schemas=todo -user=postgres -password=mypassword -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
