version: "3.8"
services:
  todo:
    image: ${REGISTRY:-local}/todo.cicd:${TAG:-latest}
    build:
      context: ./todoapp
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - "DATABASE_URL=postgres://postgres:mypassword@localhost:5432/postgres?pool_max_conns=10&currentSchema=todo"

  myflyway:
    image: ${REGISTRY:-local}/myflyway:${TAG:-latest}
    build:
      context: ./migrations
      dockerfile: Dockerfile
