{{- $fullName := include "lidlpay.fullname" . -}}
{{- $name := include "lidlpay.name" . -}}
{{- $chart := include "lidlpay.chart" . -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- $imageRegistry := .Values.imageRegistry }}
{{- $imageTag := .Values.imageTag }}
{{- $imagePullSecret := .Values.imagePullSecret }}
{{- $configurations := .Values.configurations }}
{{- $secrets := .Values.secrets}}

{{- range .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" $fullName .name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/managed-by: {{ $releaseService }}
spec:
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "%s-%s" $name .name }}
      app.kubernetes.io/instance: {{ $releaseName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ printf "%s-%s" $name .name }}
        app.kubernetes.io/instance: {{ $releaseName }}
    spec:
      imagePullSecrets:
        - name: {{ $imagePullSecret }}
      containers:
        - name: {{ .name }}
          image: "{{ printf "%s/%s:%s" $imageRegistry .image $imageTag }}"
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
          env:
            {{- range $key, $value := $configurations }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- range $key := $secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: "{{ printf "%s-secrets" $fullName }}"
                  key: {{ $key}}
            {{- end }}
          ports:
            {{- range .ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80 
          resources:
            {{- toYaml .resources | nindent 12 }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
{{- end }}


