{{- $fullName := include "lidlpay.fullname" . -}}
{{- $name := include "lidlpay.name" . -}}
{{- $chart := include "lidlpay.chart" . -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- $namespace := .Values.namespace -}}
{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $fullName .name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/managed-by: {{ $releaseService }}    
    app.kubernetes.io/service: {{ .name }}
spec:
  ports:
    {{- range .ports }}
    - port: {{ .port }} 
      targetPort: {{ .name }}
      protocol: TCP
      name: http
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ printf "%s-%s" $name .name }}
    app.kubernetes.io/instance: {{ $releaseName }}
---
{{- if ( .monitoring ) and eq .monitoring true }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-monitor" .name}}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/service: {{ .name }}
  namespaceSelector:
    matchNames:
    - {{ $namespace }}
  endpoints:
  - port: http
    path: /metrics
{{- end }}
---
{{- end }}