{{- $fullName := include "lidlpay.fullname" . -}}
{{- $name := include "lidlpay.name" . -}}
{{- $chart := include "lidlpay.chart" . -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- $imageRegistry := .Values.imageRegistry }}
{{- $imageTag := .Values.imageTag }}
{{- $imagePullSecret := .Values.imagePullSecret }}

{{- range .Values.testspayments }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ printf "%s-%s" $fullName .name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/managed-by: {{ $releaseService }}
  annotations:
    "helm.sh/hook": test-success
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  imagePullSecrets:
    - name: {{ $imagePullSecret }}
  containers:
    - name: {{ .name }}
      image: "{{ printf "%s/%s:%s" $imageRegistry .image $imageTag }}"
      env:
        {{- range $key, $val := .env }}
      - name: {{ $key }} 
        value: {{ $val | quote}}
        {{- end }}
        {{- range $key := .secrets }}
      - name: {{ $key }}
        valueFrom:
          secretKeyRef:
            name: "{{ printf "%s-secrets" $fullName }}"
            key: {{ $key}}
        {{- end }}

      command: ["sh", "-c", "{{ .command }}"]
  restartPolicy: Never
---
{{- end }}