deployments:
  todo-api:
    environment:
      DATABASE_URL: "postgres://postgres:mypassword@todo-cicd-staging-postgresql:5432/postgres?pool_max_conns=10"
      HOST: "http://cicdexample.com/staging/todoapi"

jobs:
  myflyway:
    environment:
      FLYWAY_URL: "jdbc:postgresql://todo-cicd-staging-postgresql/"
