{{- $fullName := include "fullname" . -}}
{{- $name := include "name" . -}}
{{- $chart := include "chart" . -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- $namespace := .Values.namespace -}}
{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $fullName .name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/managed-by: {{ $releaseService }}    
    app.kubernetes.io/service: {{ .name }}
spec:
  ports:
    {{- range .ports }}
    - port: {{ .port }} 
      targetPort: {{ .name }}
      protocol: TCP
      name: http
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ printf "%s-%s" $name .name }}
    app.kubernetes.io/instance: {{ $releaseName }}
---
{{- end }}